export default {
  INITIALIZE_SORTING_LIST: 'INITIALIZE_SORTING_LIST',
  SET_NAME: 'SET_NAME',
  SET_NAMES: 'SET_NAMES',
  SET_GREETING: 'SET_GREETING',
  SET_SELECTOR_NAMES: 'SET_SELECTOR_NAMES',
};
