export default {
  INITIALIZE_SORTING_LIST: 'INITIALIZE_SORTING_LIST',
  RESET_NAMES: 'RESET_NAMES',
  SET_NAME: 'SET_NAME',
  SET_NAMES: 'SET_NAMES',
  SET_GENDER_TYPE: 'SET_GENDER_TYPE',
  SET_GREETING: 'SET_GREETING',
  SET_SELECTOR_NAMES: 'SET_SELECTOR_NAMES',
  SORT_SELECTOR_NAMES: 'SORT_SELECTOR_NAMES',
};
